# Generated by Django 5.1.6 on 2025-02-15 14:21

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=300)),
                ('image', models.FileField(blank=True, upload_to='')),
                ('order', models.IntegerField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrandDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to='')),
                ('hero_media', models.FileField(blank=True, upload_to='')),
                ('efficiency_title', models.CharField(blank=True, max_length=500)),
                ('efficiency_description', models.TextField(blank=True)),
                ('efficiency_image', models.FileField(blank=True, upload_to='')),
                ('why_right_choice_title', models.CharField(blank=True, max_length=500)),
                ('why_right_choice_description', models.TextField(blank=True)),
                ('what_makes_different', models.TextField(blank=True)),
                ('what_makes_different_image', models.FileField(blank=True, upload_to='')),
                ('left_content', ckeditor.fields.RichTextField(blank=True)),
                ('right_content', ckeditor.fields.RichTextField(blank=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_details', to='brand.brandmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
